# Generated by Django 4.0.6 on 2022-07-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='kod',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='zobrazit',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='hodnota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='attributes_ids',
            field=models.ManyToManyField(blank=True, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='products_ids',
            field=models.ManyToManyField(blank=True, to='api.product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='obrazek',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='product',
            name='cena',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mena',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='nazev',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
