# Generated by Django 4.0.6 on 2022-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attributename_kod_alter_attributename_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.CharField(max_length=255),
        ),
    ]
